T-REX-XP/SSDPFinder

modules/ssdpdevices/ssdpdevices_structure.inc.php
Методы запускаются но как их вызвать ?
=> Добавлено устройство и два метода

modules/ssdp_finder/ssdp_devices_edit.inc.php, modules/ssdpdevices/SMediaRenderer_playUrl.php, modules/ssdpdevices/ssdpdevices_structure.inc.php
воспроизводит урл файоі из инета по крайней мере, надо тестировать
=> Добавлено playUrl

modules/ssdp_finder/ssdp_devices_edit.inc.php, modules/ssdp_finder/ssdp_finder.class.php, templates/ssdp_finder/ssdp_devices_edit.html
Теперь исправлено иссу можеш закріть
=> Все таки исправил местоположение для устройств (room)

modules/ssdp_finder/ssdp_finder.class.php
Теперь должно запускать автоматически проверку
=> Исправлен автозапуск проверки устройства онлайн

modules/ssdp_finder/ssdp_devices_edit.inc.php, modules/ssdp_finder/ssdp_finder.class.php, modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Renderer.php, modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Renderer/Remote.php, modules/ssdpdevices/SMediaRenderer_playNextUrl.php, modules/ssdpdevices/SMediaRenderer_volume.php, modules/ssdpdevices/ssdpdevices_structure.inc.php, templates/ssdp_finder/ssdp_devices_edit.html
Звук - mute-unmute 
leve
Play url
play next url
=> Добавлено управление звуком и воспроизведение ссылки

modules/ssdp_finder/ssdp_devices_edit.inc.php, modules/ssdp_finder/ssdp_devices_scan.inc.php, modules/ssdp_finder/ssdp_finder.class.php, modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Renderer.php, modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Renderer/Remote.php, templates/ssdp_finder/ssdp_devices_edit.html, templates/ssdp_finder/ssdp_devices_scan.html
=> Удалено за ненадобностью

modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Renderer/Remote.php, modules/ssdpdevices/ssdpdevices_structure.inc.php
=> Пропал АЙПИ адрес

modules/ssdpdevices/SMediaRenderer.template
Темная тема и светлая тема. 
Темная намного лучше
=> Исправлено отображение панели по стилях

my notate.txt
=> Update my notate.txt

modules/ssdp_finder/ssdp_devices_scan.inc.php
Исключены из поиска устройства которые уже задействованы
=> Мелкие исправления

modules/ssdp_finder/ssdp_devices_edit.inc.php, modules/ssdp_finder/ssdp_finder.class.php, templates/ssdp_finder/ssdp_devices_scan.html, templates/ssdp_finder/ssdp_devices_search_admin.html
Исправления мелкие не влияющие на работоспособность модуля
=> Внесены несколько исправлений 

modules/ssdpdevices/SMediaRenderer.template, modules/ssdpdevices/SMediaServer_getFileList.php, modules/ssdpdevices/medaiserver.urllist.php
Обновлен пульт управления устройствами для воспроизведения видео
=> Обновлено управление MediaRenderer

modules/ssdpdevices/SMediaRenderer.template, modules/ssdpdevices/medaiserver.urllist.php
Устройства медиарендерер теперь лучше управляються
=> Исправлено и улучшено пульт

modules/ssdpdevices/medaiserver.urllist.php
=> косметические исправления

modules/ssdpdevices/SMediaRenderer.template
- заблокировал дропдауны если не выбран тип
- фикс для Chrome Linux
=> косметические исправления интерфейса

modules/ssdpdevices/SMediaRenderer.template
- форматирование выпадающих списков
- поддержка верстки для Chrome Linux
=> форматирование выпадающих списков

modules/ssdp_finder/upnp/vendor/jalder/upnp/examples/upnp.renderer.php, modules/ssdpdevices/SMediaRenderer_playUrl.php
Теперь она запускает видео независимо от того играет что то или нет
=> Исправлена функция Плей

modules/ssdp_finder/ssdp_finder.class.php
Поскольку в мажордомо появился терминал днла то есть смысл изменить тип терминала
=> Исправлено тип терминала

modules/ssdp_finder/ssdp_finder.class.php
Пока тут ошибка но простых устройств не удаляет...
=> Вернул деинсталляцию

modules/ssdp_finder/ssdp_finder.class.php
Теперь удаляет устройства, терминалы, устройства онлайн, только те что были созданы самим модулем...
Перепривязка устройств к другому обьекту  в дальнейшем не удалит выше упомянутых записей
=> Исправлено удаление устройств

modules/ssdp_finder/ssdp_finder.class.php
Теперь удаляет оба модуля без затрагивания простых устройств правда остается мусор от модуля ssdpdevices. Но модуля отсутствуют в списках.
=> Исправлено удаления модулей

modules/ssdp_finder/ssdp_finder.class.php
Теперь удаляет все базы которые создаются модулем
=> Не происходило удаление базы данных

modules/ssdpdevices/SMediaServer_getFileList.php
Исправлено получение локального адреса айпи при условии использования устройства на локальной системе
=> Исправлено получение списка с локальным айпи

modules/ssdpdevices/ssdpdevices.class.php
Ошибка. при удалении удаляет простые устройства поэтому деинсталяция отключена
=> Отключена деинсталяция

modules/ssdp_finder/ssdp_finder.class.php
Теперь полностью удаляет модуль и все созданные с его помощью устройства , а также устройства онлайн, терминалы.
=> Исправлено удаление модуля

templates/classes/views/SInternetGatewayDevice.html
Для того что бы не вставлять HTML код вручную из файла SInternetGatewayDevice.template. Он будет подтягиваться из папки htdocs\templates\classes\views
=> Автоматическое добавление шаблона для шлюза

modules/ssdp_finder/ssdp_devices_scan.inc.php
=> Нужное обновление 

modules/ssdp_finder/ssdp_finder.class.php
Теперь заполняет свойства устройств - такие как groupSunrise, groupEcoOn. groupEco, linkedRoom.
По умолчанию.
=> Обновление связанное с заполнением свойств

modules/ssdp_finder/ssdp_finder.class.php, templates/classes/views/SMediaServer.html
Как не проверял вроде все получается
=> Исправлен шаблон МедиаСервера

modules/ssdp_finder/ssdp_finder.class.php
Поскольку стандартная функция исправлено то из модуля она убрана
=> Убрана функция создания простых устройств

templates/classes/views/SBinaryLight.html, templates/classes/views/SControllee.html, templates/classes/views/SInternetGatewayDevice.html, templates/classes/views/SMediaRenderer.html, templates/classes/views/SMediaServer.html
Теперь Галочка обозначает на связи , а крестик не на связи
=> Исправлен шаблон роутера

modules/devices/SBinaryLight_turnOff.php, modules/devices/SBinaryLight_turnOn.php, modules/devices/SControllee_turnOff.php, modules/devices/SControllee_turnOn.php, modules/devices/SMediaServer_getFileList.php
Добавлена обратная связь на срабатывание устройства.
=> Добавлена проверка на срабатывание устройства.

modules/devices/SBinaryLight_turnOff.php, modules/devices/SBinaryLight_turnOn.php, modules/devices/SControllee_turnOff.php, modules/devices/SControllee_turnOn.php, templates/classes/views/SBinaryLight.html, templates/classes/views/SControllee.html
При произношении от того что не сработало устройство  исправлена ошибка
=> Исправления в названии обьекта

modules/ssdp_finder/ssdp_devices_search.inc.php, modules/ssdp_finder/ssdp_finder.class.php
Поскольку в устройстве может быть отключена какая то служба, но а устройство пингуется, то введена проверка на пингование хмл файла соответствующей службы. 
Необходимо Удалить из онлайн устройств служби и поновому их создать.
=> Исправлена функция для создания Хост Онлайн.

modules/ssdp_finder/ssdp_devices_edit.inc.php, modules/ssdp_finder/ssdp_finder.class.php
Ошибки допущены в коде
Добавлена функция SAYTO для воспроизведения системных сообщений на созданный модулем терминал.
=> Исправлены мелкие ошибки

modules/ssdp_finder/ssdp_finder.class.php
Поскольку Сергей в мажорике сломал функцию добавления устройств то пришлось перенести ее к себе в класс
=> Исправлено функцию добавления устройств 

templates/classes/views/SInternetGatewayDevice.html, templates/classes/views/SMediaRenderer.html, templates/classes/views/SMediaServer.html
В связи с ремонтом загрузки bootstrap в сценах убрана подгрузка бутстрапа в шаблонах
=> Обновления

modules/ssdp_finder/ssdp_devices_scan.inc.php, templates/ssdp_finder/action_admin.html, templates/ssdp_finder/ssdp_devices_scan.html
Отключена кнопка установки модуля при условии его наличия в системе
=> Исправление кнопки внешних модулей

modules/ssdp_finder/ssdp_finder.class.php, modules/ssdp_finder/update_methods.inc.php, templates/ssdp_finder/action_admin.html, templates/ssdp_finder/ssdp_devices_edit.html
Теперь кнопка обновить появляется только тогда когда есть обновления драйверов для устройств
=> Исправлено кнопку обновить

modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Core.php
Теперь управляет и теми устройствами что находятся на сервере
=> Управляет локальными устройствами

modules/ssdp_finder/ssdp_devices_edit.inc.php, modules/ssdp_finder/ssdp_devices_scan.inc.php, templates/ssdp_finder/ssdp_devices_edit.html
=> Изменена запись типа сервиса устройства

modules/ssdp_finder/extended_modules.php, modules/ssdp_finder/ssdp_devices_scan.inc.php, modules/ssdp_finder/ssdp_install_module.inc.php, modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Core.php
А также возможная ошибка поиска
=> Исправлен способ инициализации модулей

modules/ssdp_finder/upnp/vendor/jalder/upnp/src/Core.php
=> Возврат назад - не работает

modules/ssdp_finder/ssdp_devices_edit.inc.php, modules/ssdp_finder/ssdp_finder.class.php, templates/ssdp_finder/ssdp_devices_edit.html
за ненадобностью - теперь терминалы это делают
=> убрана кнопка - использовать для системных сообщений
